url: https://dvll.io
enforce_ssl: dvll.io

# Site settings
title: dvll.io
description: "My personal page, build with Jekyll."
url: "http://dvll.io"
author:
  name: "Romain Deville"
  email: "romain@dvll.io"
  url: "http://dvll.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
